[package]
name = "unit-splitter-core"
version = "0.2.0"
authors = ["LeRoyce Pearson <leroycepearson@geemili.xyz>"]
edition = "2018"

[dependencies]
failure = "0.1"
failure_derive = "0.1"
pest = "*"
pest_derive = "*"
