[package]
name = "unit-splitter-gtk"
version = "0.1.0"
authors = ["LeRoyce Pearson <leroycepearson@geemili.xyz>"]

[dependencies]
unit-splitter-core = { path = "../core" }
gtk = "^0.3.0"
relm = "^0.11.0"
relm-derive = "^0.11.0"
