[package]
name = "unit_splitter_web"
version = "0.2.0"
authors = ["LeRoyce Pearson <leroycepearson@geemili.xyz>"]
edition = "2018"

[profile.release]
lto = true

[dependencies]
draco = { path = "../../../tmp/draco" }
wasm-bindgen = "0.2.25"
unit-splitter-core = { path = "../core" }
