[package]
name = "unit_splitter_web"
version = "0.1.0"
authors = ["LeRoyce Pearson <leroycepearson@geemili.xyz>"]

[dependencies]
stdweb = "0.4"
yew = { git = "https://github.com/DenisKolodin/yew/" }
unit-splitter-core = { path = "../core" }
